# Lesson 12: Linear Algebra basics with python
The goal of this lesson is to get introduce and get aquainted with some basic structures like vectors, matrices, and routine linear algebra functions in python.

In [12]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### building matrices and vectors with numpy
We use numpy arrays to make both matrices and vectors in python. A matrix is an array of arrays, where each row of the matrix is an array. A row vector is just a numpy array and a column vector is an array of 1-element arrays, just like an $n\times 1$ matrix.

Let's make the objects below.

$$A = \begin{bmatrix} 3 & 4 & 5 \\ 2&3&5 \\ 3&6&9 \end{bmatrix}$$

$$\vec{u} = \begin{bmatrix} 1& 2 &3 \end{bmatrix}$$

$$\vec{v} = \begin{bmatrix} 10 \\ 20 \\ 30 \end{bmatrix}$$

In [19]:
A = np.array([ [3, 4,5],
             [2, 3, 5],
             [3, 6, 9]])
u = np.array([[1,2,3]])
v = np.array([[10],
             [20],
             [30]])

In [14]:
print(A)

[[3 4 5]
 [2 3 5]
 [3 6 9]]


In [20]:
print(u.transpose())

[[1]
 [2]
 [3]]


In [22]:
print(v.transpose())

newv = np.array([[10, 20, 30]]).transpose()

print(newv)

[[10 20 30]]
[[10]
 [20]
 [30]]


In [24]:
print(f"{np.linalg.det(A):4.4f}")

#det not equal to zero means the inverse exists

Ainv = np.linalg.inv(A)

print(Ainv)



-6.0000
[[ 0.5         1.         -0.83333333]
 [ 0.5        -2.          0.83333333]
 [-0.5         1.         -0.16666667]]


### Kirchoff's Laws

### Introduction.

Consider the Pixar short "For the birds."

```{image} ./kirchoff1.png
:alt: three loop circuit 
:width: 500px
:align: center
```

The multiloop circuit shown above has two junctions and three branches carrying currents, $I_1, I_2, I_3$. Kirchoff's Voltage Law says that the sum of the voltage drops around any loop must be zero. The voltage drop across a resistor is given by Ohm's Law ($V=IR$) where $I$ is the current and $R$ is the resistance. Kirchoff's Current Law says that the sum of the currents at any junction must be zero (direction is important).

Explain why the system below for the currents follows from Kirchoff's Laws.

\begin{align}
I_1 - I_2 + I_3 &= 0 \\
-I_1 + I_2 - I_3 &= 0 \\
4I_1 + 2I_2 + 3I_1 &= 5 \\
6I_3 + 2I_2 &=10 \\
6I_3 - 4I_1 - 3I_1 &=-5 + 10
\end{align}

Which equations above represent redundant information? Why?

Represent this system with matrix and vector objects in python.

\begin{align}
I_1 - I_2 + I_3 &= 0 \\
4I_1 + 2I_2 + 3I_1 &= 5 \\
6I_3 + 2I_2 &=10 \\
\end{align}

$$\begin{bmatrix}1 & -1 & 1 \\
7 & 2 & 0 \\
0 & 2 & 6 \end{bmatrix} \begin{bmatrix} I_1 \\ I_2 \\I_3 \end{bmatrix} = \begin{bmatrix}0 \\5\\10\end{bmatrix} $$

In [25]:
#write as Ax = b. 
#need matrix for A and vector for b

A = np.array([[1, -1, 1],
             [7,2,0],
             [0,2,6]])
b = np.array([[0,5,10]]).transpose()

In [26]:
print(A)
print(b)
print(A.shape)
print(b.shape)

[[ 1 -1  1]
 [ 7  2  0]
 [ 0  2  6]]
[[ 0]
 [ 5]
 [10]]
(3, 3)
(3, 1)


In [27]:
x = np.linalg.solve(A,b)
print(x)

[[0.29411765]
 [1.47058824]
 [1.17647059]]


### Dot and cross products

Calculate the dot and cross products, and find the angle between the vectors below.

$$\vec{a} = \begin{bmatrix} 4 \\ 2 \\ 1\end{bmatrix}, \hspace{1cm} \vec{b} = \begin{bmatrix} 1 \\ 1 \\ 1\end{bmatrix} $$

In [30]:
a = np.array([[4,2,1]]).T #note .T and .transpose both compute a transpose and convert a row vector to a column vector
b = np.array([[1,1,1]]).transpose()

print(a)
print(b)

[[4]
 [2]
 [1]]
[[1]
 [1]
 [1]]


In [32]:
np.dot(a.T,b)

array([[7]])

In [35]:
np.cross(a.T,b.T).T

array([[ 1],
       [-3],
       [ 2]])