# Lesson 13: Linear Algebra - eigenvalues
Equations and eigenvalues

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sympy import *  #import sympy routines; sympy = "SYMbolic PYthon"

### Wheatstone bridge example

The resistor network shown below is a Wheatstone bridge. It can be used to calculate unknown resistances of objects.
The current through resistor $R_5 = 0$ when $R_1R_4=R_2R_3$, so if we know $R_3$ and $R_4$ and make $R_2$ a variable resistor and have $R_1$ be the unknown, we can tune $R_2$ while measuring the current through $R_5$ to find $R_1$.


```{image} ./wheatstone.jpg
:alt: Wheatstone bridge circuit 
:width: 300px
:align: center
```



A more general problem is to compute the currents through each resistor. Using Ohm's Law and Kirchoff's Voltage Law we can calculate the mesh currents $x_1, x_2, x_3$ using the equations below.

\begin{align*}
(R_1 + R_3 + R_5) x_1 - R_5 x_2 -R_3x_3 &= 0\\
-R_5 x_1 + (R_2 + R_4 + R_5) x_2 - R_4 x_3 &= 0\\
-R_3 x_1 - R_4x_2 + (R_3 + R_4 + R_6)x_3 &= V
\end{align*}

Then $i_1 = x_1, i_2 = x_2, i_3 = x_3-x_1, i_5=x_1-x_2,$ and $i_6 = x_3$.

Let $R_i = 10 \hspace{4mm} \forall i$ and let $V=5$. Set up and solve these equations for $x_1, x_2, x_3$ below.

In [9]:
A = np.array([[40, -10, -10],
             [-10,30,-10],
             [-10,-10,30]])

b = np.array([[0],
             [0],
             [5]])

newb = np.array([[0,0,5]]).transpose()

#print(newb)

x = np.linalg.solve(A,newb)

print(x)


[[0.08333333]
 [0.10416667]
 [0.22916667]]


### Chemical reaction example
 
Balance the chemical reaction below.

$$x_1 Cu_2S + x_2H^+ + x_3 NO^-_3 \longrightarrow x_4Cu^{2+} + x_5 NO + x_6 S_8 + x_7H_2O$$


In [ ]:
#show np.linalg.solve doesn't work

#use sympy Matrix and M.rref() command  
#relate back to Math250, Math 275



### Chemical reaction example
 
Balance the chemical equation for the combustion of butane liquid (C4H10) in the presence of oxygen gas to yield carbon dioxide and water in the gaseous phase:

$$C_4H_{10} + O_2 \longrightarrow CO_2 + H_2O$$



In [10]:
A = np.array([[4,0,-1,0],
             [10,0,0,-2],
             [0,2,-2,-1]])

b = np.array([[0,0,0]]).transpose()

x = np.linalg.solve(A,b)

LinAlgError: Last 2 dimensions of the array must be square

In [11]:
from sympy import *

A = Matrix([[4,0,-1,0],
             [10,0,0,-2],
             [0,2,-2,-1]])

print(A.rref())

(Matrix([
[1, 0, 0,   -1/5],
[0, 1, 0, -13/10],
[0, 0, 1,   -4/5]]), (0, 1, 2))


**Exercise** Balance the chemical reaction below.

$${\mathrm C}_6{\mathrm H}_{12}{\mathrm O}_6\;(s)\;+\;{\mathrm O}_2\;(g)\;\rightarrow\;{\mathrm{CO}}_2\;(s)\;+\;{\mathrm H}_2\mathrm O\;(l)$$

### Calculate eigenvalues

Calculate the eigenvalues of the matrix below using the [eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html) command of the numpy library.

$$A = \begin{bmatrix} 1 & 2 & 3\\4& 5&6 \\ 7&8&1\end{bmatrix}$$

In [12]:
A = np.array([[1,2,3],[4,5,6],[7,8,1]])

w,v = np.linalg.eig(A)

print(w)

print(v)


[12.45416474 -0.37976219 -5.07440255]
[[-0.29373774 -0.73967882 -0.29720654]
 [-0.69005397  0.66500848 -0.39870229]
 [-0.66147083 -0.10314536  0.86758559]]


### System of linear ODEs example

Set up a system of differential equations that represent the amount of salt in the tanks below.
Then use the eig command to help you determine the solution.

```{image} ./tanks.png
:alt: multi tank system 
:width: 300px
:align: center
```


<div>
<img src="attachment:brine_tanks.jpg" width="500"/>
</div>

In [13]:
A = np.array([[-.3,0.05],
              [.3,-.15]])

w,v = np.linalg.eig(A)

In [14]:
print(w)
print(v)

[-0.36861407 -0.08138593]
[[-0.58893305 -0.22295647]
 [ 0.80818183 -0.9748284 ]]


In [15]:
c = np.linalg.solve(v,np.array([[10,11]]).T)

In [16]:
print(c)

[[ -9.67225498]
 [-19.3028236 ]]
